### ISSUE TITLE
beehive don`t need to handle yaml or commandline config

### ISSUE THREAD

**Issue by kadisi** [kubeedge/beehive#14]
the core function of beehive is  handling the cross-module communication.  but it also handle config (such as commandline config and yaml config).

i think beehive don`t need to handle those config.  we need let kubeedge to handle it .

This will lead to greater flexibility。

this is an example:

if we want `edge_core` output current detail version. it`s going to be very difficult.

because edge_core first import `github.com/kubeedge/beehive/pkg/core`, and `"github.com/kubeedge/beehive/pkg/core"` will import `"github.com/kubeedge/beehive/pkg/common/config"`. and they will output many log info rather than only output current version.

**Comment by rohitsardesai83** [comment]
@qizha , thoughts ?
